- name: Deploy Prometheus Node Exporter
  hosts: all
  - name: Removing
    file:
      path: "/tmp/workingDir/"
      state: absent

  tasks:
    - name: Get Node Exporter from prometheus GitHub
      debug:
        msg: "start Prometheus Node Exporter deployment"

    - name: Create temporary Working directory
      file: path=/tmp/workingDir state=directory 

    - name: Download Node Exporter Tarball
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v0.17.0-rc.0/node_exporter-0.17.0-rc.0.linux-amd64.tar.gz
        dest: /tmp/workingDir/install.tar.gz
        mode: 0755 

    - name: Create temporary Archive
      file: path=/tmp/workingDir/installDir state=directory

    - name: Unpackage
      unarchive:
        src: /tmp/workingDir/install.tar.gz
        dest: /tmp/workingDir/installDir
        remote_src: yes

    - name: Launch Prometheus on Node
      shell: /tmp/workingDir/installDir/node_exporter-0.17.0-rc.0.linux-amd64/node_exporter
